### ISSUE TITLE
All aboard card has a typo

### ISSUE THREAD

**Issue by eduardojmatos** [jreisstudio/stopflyingblindgame#2]
Hey folks! First, thank you for this awesome repository!

I was looking for the cards and I see a typo, at the "All aboard" card. 

"Business agility is not a _tem_ sport but a company sport".

https://github.com/jreisstudio/stopflyingblindgame/blob/master/%2305.jpeg

It's a minor typo, but just informing you @jreisstudio :)

**Comment by jreisstudio** [comment]
Hi Eduardo!  It's fixed in the miro board version (the one we are working
now...),by the way, thanks for reporting that!

**Comment by eduardojmatos** [comment]
Thanks, @jreisstudio, I'll be tuned on the Miro version :)
